name: build-apk
on: push

jobs:
  release-to-gitHub:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.9.1+hotfix.2"
      - run: flutter upgrade
      - run: flutter pub get  
      #- run: flutter analyze --no-pub --no-current-package lib/ test/
      - run: flutter test --no-pub test/
      - run: flutter build apk
      # upload apk
      - uses: actions/upload-artifact@v1
        with:
          name: android apk
          path: build/app/outputs/apk/debug/app-debug.apk
